[formatting]
line_length = 79

[keymap]
preset = "vim"
[keymap.overrides]

[runtime]
auto_instantiate = true
std_stream_max_bytes = 1000000
on_cell_change = "autorun"
reactive_tests = true
default_sql_output = "auto"
auto_reload = "off"
watcher_on_save = "lazy"
output_max_bytes = 8000000

[language_servers.pylsp]
enable_pydocstyle = false
enable_flake8 = false
enable_ruff = true
enable_mypy = true
enable_pylint = false
enabled = true
enable_pyflakes = false

[experimental]

[completion]
activate_on_typing = true
copilot = "github"

[server]
browser = "default"
follow_symlink = false

[ai]
rules = ""
[ai.google]

[ai.bedrock]

[ai.open_ai]

[ai.anthropic]

[diagnostics]

[package_management]
manager = "uv"

[snippets]
include_default_snippets = true
custom_paths = []

[display]
default_table_page_size = 10
code_editor_font_size = 14
cell_output = "below"
dataframes = "rich"
theme = "dark"
default_width = "medium"

[save]
format_on_save = false
autosave = "after_delay"
autosave_delay = 1000
