name: update-flake-lock

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 3 * * *'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'carve'
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: rde
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: rstats-on-nix, nix-community
      - run: cd templates/rde/ && nix develop -c p-updateDeps
      - name: Update n flake.lock
        uses: DeterminateSystems/update-flake-lock@v27
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          branch: update_rde
          path-to-flake-dir: "templates/rde"
          pr-title: "Update RDE flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated
