name: update-flake-lock

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 3 * * *'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Update n flake.lock
        uses: DeterminateSystems/update-flake-lock@v25
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          branch: update_n
          path-to-flake-dir: "templates/n"
          pr-title: "Update n flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated
